### ISSUE TITLE
2020分野3 第1問(4) a) 符号ミス？

### ISSUE THREAD

**Issue by hewlae** [KaiNakao/civil-inshi#27]
運動量保存則の符号が逆ではないでしょうか…？ cf. 明解水理学 p.124 式6.49

**Comment by hewlae** [comment]
@KaiNakao

**Comment by KaiNakao** [comment]
逆だね、適当に編集してもらって大丈夫です。

**Comment by KaiNakao** [comment]
運動量の変化は流出が正！！！！！！！
運動量の変化は流出が正！！！！！！！
運動量の変化は流出が正！！！！！！！
運動量の変化は流出が正！！！！！！！
運動量の変化は流出が正！！！！！！！

**Comment by hewlae** [comment]
よくわからないのだけれどLaTeXの環境が違うせいでコンパイルがバグり倒しています、放ったらかしにしてもいいですか………

**Comment by KaiNakao** [comment]
どんまい、
