### ISSUE TITLE
2022年分野4 第1問

### ISSUE THREAD

**Issue by Tokiwa-eng** [KaiNakao/civil-inshi#28]
(2)について，F=5のときはx_waittimeが変わるので，x_cng = 0だとしてもV_OWは(1)と同じにはならなさそうです．
@yH3PO4

**Comment by yH3PO4** [comment]
確かにです。

**Comment by yH3PO4** [comment]
https://github.com/KaiNakao/civil-inshi/blob/28-fix/field4/2022/main.md#2

これでどうでしょうか。
