### ISSUE TITLE
2019年 分野3 第2問(3)(d) モリモリ積分

### ISSUE THREAD

**Issue by hewlae** [KaiNakao/civil-inshi#39]

**Comment by hewlae** [comment]
https://www.wolframalpha.com/input?i=2%CF%80*Integrate%5B%28%28a%5E2+-+r%5E2%29G%29%2F%284%CE%BC%29%2B%283Ga%5E2+log%28r%2Fa%29%29%2F%284+log%282%29+%CE%BC%29%2C+%7Br%2C+a%2C+2a%7D%5D&lang=ja
wolframくんに投げたら、積分結果は
π a^3 G (14 log(2) - 9))/(μ log(64))
こうだよと言ってる

**Comment by hewlae** [comment]
@KaiNakao ごめんなさい メンション忘れてました

**Comment by KaiNakao** [comment]
ヤコビアンのrが必要なんで、、
https://www.wolframalpha.com/input?i=2π*Integrate%5B%28%28%28a%5E2+-+r%5E2%29G%29%2F%284μ%29%2B%283Ga%5E2+log%28r%2Fa%29%29%2F%284+log%282%29+μ%29%29r%2C+%7Br%2C+a%2C+2a%7D%5D&lang=ja

**Comment by hewlae** [comment]
あっ 完全忘却してた すみませんでした
