### ISSUE TITLE
2019年 分野3 第2問(3)e) 円柱に作用する力

### ISSUE THREAD

**Issue by hewlae** [KaiNakao/civil-inshi#40]
1. まず、rがそのまま解答に残ってはいけないような気がしています。円柱の側面にかかる力なので、r=aを代入すべきなのでは？
2. また、壁面剪断応力はτ=ρgRIの式を使うイメージがあるんですが、これとτ=μ∂u/∂r って一致するんでしょうか…？意見を聞きたいです

**Comment by hewlae** [comment]
@KaiNakao ごめんなさい メンション忘れてました

**Comment by KaiNakao** [comment]
1.しゅうせいしました
https://github.com/KaiNakao/civil-inshi/tree/40-2019-field-3-rev
2.τ=ρgRIは開水路 or 大きな管路の壁面近くで成り立つ式だと思っている(ここは持論)
管路流れの講義資料ではせん断応力がどこでも同じとして力のつり合いを立式していて、この問題はそんなではなさそう

**Comment by hewlae** [comment]
1. ありがとうございます
2. せん断応力がどこでも同じじゃないのでτ=ρgRIではどうにもなりません、というのが実際のところですかね。普通にμ∂u/∂rが壁面でも使えるのに対してそうなんだという気持ちになった、という感じでした
